### ISSUE TITLE
Use opening_hour tags in display

### ISSUE THREAD

**Issue by jbelien** [CityZenApp/CityZen-Android#18]
When you list the POI's in the app, would be really useful to easily see if the POI is currently open or closed (comparison between current time and `opening_hours` tag)

**Comment by rskikuli** [comment]
Tis feature is already implemented @jbelien. Inf you go on top right corner of the results page of each category you can filter results by 'currently opened'. Have a look at the screenshot please.  ![cityzen_app_alpha_testing_2017-08-22_15-01-37](https://user-images.githubusercontent.com/17770262/29566670-e58095f8-874a-11e7-8101-935caa046b3e.jpg)

**Comment by jbelien** [comment]
So sorry ...
I'll be more careful next time !
